project:
  type: website

website:
  navbar:
    logo: images/logo.png
    background: "#FFD700"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: 概要
      - href: activity.qmd
        text: 活動実績
      - href: contact.qmd
        text: 連絡フォーム

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    header-includes: |
      <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
      <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          AOS.init();
        });
      </script>
    toc: true

editor: visual

